name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      run_it: >-
        ${{
        steps.skip_check.outputs.should_skip != 'true' ||
        github.ref_name == 'main'
        }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer

  stack:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.run_it == 'true' }}
    uses: ./.github/workflows/stack.yml
    secrets: inherit
    with:
      cache: v2

  cabal-install:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.run_it == 'true' }}
    uses: ./.github/workflows/cabal-install.yml
    secrets: inherit
    with:
      cache: v2
