name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  stack:
    uses: ./.github/workflows/stack.yml
    secrets: inherit
    with:
      cache: v2

  cabal-install:
    uses: ./.github/workflows/cabal-install.yml
    secrets: inherit
    with:
      cache: v2
