name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

env:
  cache-version: v1

defaults:
  run:
    shell: bash

jobs:
  stack:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on:
      - ${{ matrix.os }}

    env:
      STACK_BUILD:
        stack build --test --coverage --bench

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache stack
        uses: freckle/stack-cache-action@v2

      - name: Show stack version
        run: |
          stack --version
          stack exec -- ghc --version

      - name: Set stack to use system ghc
        run: stack config set system-ghc --global true

      - name: Install dependency packages
        run: $STACK_BUILD --only-dependencies miniterion

      - name: Build
        run: $STACK_BUILD --no-run-tests --no-run-benchmarks miniterion

      - name: Run tests and benchmarks
        run: $STACK_BUILD --test-arguments "+RTS -T" miniterion

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v2
        with:
          target: stack:miniterion-test

      - name: Send coverage report
        uses: codecov/codecov-action@v3
        with:
          name: miniterion-test-${{ matrix.os }}

  cabal-install:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        plan:
          - ghc: "9.2.8"
            cabal : "3.6.2.0"
          - ghc: "9.4.7"
            cabal: "3.8.1.0"
          - ghc: "9.6.2"
            cabal: "3.10.1.0"
          - ghc: "9.8.1"
            cabal: "3.10.1.0"

    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache ~/.ghcup
        id: home-dot-ghcup
        uses: actions/cache@v3
        with:
          path: ~/.ghcup
          key: ghcup-${{ runner.os }}-${{ matrix.plan.ghc }}-${{ env.cache-version }}

      - name: Cache cabal package database
        id: home-dot-cabal
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: cabal-${{ runner.os }}-${{ matrix.plan.ghc }}-${{ env.cache-version }}

      - name: Install ghc and cabal-install
        run: |
          ghcup upgrade
          ghcup install cabal ${{ matrix.plan.cabal }}
          ghcup install ghc ${{ matrix.plan.ghc }}
          ghcup set ghc ${{ matrix.plan.ghc }}
          which cabal
          which ghc

      - name: Show versions
        run: |
          ghc --version
          cabal --version

      - name: Update hackage data
        run: cabal update

      - name: Configure
        run: cabal configure -f+dev

      - name: Build
        run: cabal build

      - name: Run tests
        run: cabal test
