on:
  workflow_call:
    inputs:
      cache:
        description: cache key version
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  stack:
    name: Build and test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on:
      - ${{ matrix.os }}

    env:
      STACK_BUILD: stack build --test --coverage --bench

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache stack related directories
        uses: 8c6794b6/playing-with-github/.github/actions/setup-stack-cache@main
        with:
          cache-key: ${{ hashFiles('stack.yaml') }}-${{ inputs.cache }}

      - name: Setup haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Run stack setup
        run: stack setup

      - name: Show stack and stack ghc version
        run: |
          stack --version
          stack exec -- ghc --version

      - name: Install dependency packages
        run: $STACK_BUILD --only-dependencies miniterion

      - name: Build
        run: $STACK_BUILD --no-run-tests --no-run-benchmarks miniterion

      - name: Run tests and benchmarks
        run: $STACK_BUILD --test-arguments "+RTS -T" miniterion

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: stack:miniterion-test

      - name: Send coverage report
        uses: codecov/codecov-action@v4
        with:
          name: miniterion-test-${{ matrix.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
